version: '3.1'

services:

  postgres:
    image: 'postgres:latest'

    restart: always
    container_name: containerstore

    environment:
      POSTGRES_DB: online_store_fpt1
      POSTGRES_PASSWORD: post
      POSTGRES_USER: postgres


    ports:
      - '5432:5432'
    networks:
      - networkstore


  online_store:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - networkstore


networks:
  networkstore:
    driver: bridge
